# Generated by Django 6.0.3 on 2026-03-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangolab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('doctor_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
    ]
