# Generated by Django 6.0.3 on 2026-03-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangolab', '0003_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tu_reg_no', models.CharField(max_length=50, verbose_name='TU Registration Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('project_file', models.FileField(upload_to='projects/', verbose_name='Upload your Project File')),
            ],
        ),
    ]
